{
 "title": "alvd",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Total Stored Index",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rinx_github_io_alvd_agent_ngt_stored)"
    }
   ]
  },
  {
   "title": "Available Agents",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rinx_github_io_alvd_server_agent_count"
    }
   ]
  },
  {
   "title": "Number of Stored Index",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rinx_github_io_alvd_agent_ngt_stored",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Number of Uncommitted Index",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rinx_github_io_alvd_agent_ngt_uncommitted",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}